language: node_js
node_js:
  - 'node'

cache: npm

install:
  - npm install

script:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: gh-pages
