node_js:
  - "lts/*"

node_js:
  - 'node'

cache: npm

before_install:
  - npm i -g npm@latest

script:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: gh-pages
